version: '3.4'

services:
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: Client\Dockerfile
    depends_on:
        - webapi   

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    ports:
        - 8080:8080
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  prometheus:
    image: prom/prometheus:v2.51.1
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.3.6
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - 3000:3000