{
 "title": "App Metrics - Web Monitoring",
 "description": "Dashboard to visualize metrics captured by App Metrics ASP.NET Core Middleware, tested with App.Metrics.Formatters.Prometheus 4.3.0 - https://www.app-metrics.io/",
 "tags": [
  "app metrics",
  "general",
  "microservices"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(dotnet_build_info, env)"
    }
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(dotnet_build_info{env=\"$environment\"}, domain)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(dotnet_build_info{env=\"$environment\",domain=~\"$domain\"}, app)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(dotnet_build_info{env=\"$environment\",app=\"$application\"},container)"
    }
   },
   {
    "name": "summarize",
    "label": "Summarize",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "App Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_build_info{env=\"$environment\",app=\"$application\"}) by (version)",
     "legendFormat": "{{version}}",
     "measurement": "application.httprequests__one_minute_error_percentage_rate",
     "query": "SELECT  \"value\" FROM \"application.httprequests__percentage_error_requests\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(application_httprequests_transactions_count{env=\"$environment\",app=\"$application\",container=~\"$container\"}[$__rate_interval]))",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Error %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(application_httprequests_one_minute_error_percentage_rate{env=\"$environment\",app=\"$application\",container=~\"$container\"})",
     "measurement": "application.httprequests__one_minute_error_percentage_rate",
     "query": "SELECT  \"value\" FROM \"application.httprequests__percentage_error_requests\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(application_httprequests_active{env=\"$environment\",app=\"$application\",container=~\"$container\"})",
     "measurement": "application.httprequests__active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "timeseries",
   "description": "Apdex (Application Performance Index) allows us to monitor end-user satisfaction. It is an open industry standard that estimates the end user’s satisfaction level on an application’s response time through a score between 0 and 1.\n\nThe Apdex score is calculated based on your required SLA (Service-Level Agreement) where you can define a response time threshold of T seconds, where all responses handled in T or less seconds satisfy the end user.\n\nApdex provides three thresholds estimating end user satisfaction, satisfied, tolerating and frustrating.\n\n- Satisfied: Response time less than or equal to T seconds.\n- Tolerating: Response time between T seconds and 4T seconds.\n- Frustrating: Response time greater than 4 T seconds.\n\nT=0.5 seconds",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (app) (application_httprequests_apdex{env=\"$environment\",app=\"$application\",container=~\"$container\"})",
     "measurement": "application.httprequests__apdex",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Framework",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_build_info{env=\"$environment\",app=\"$application\"}) by (runtime_version)",
     "legendFormat": "{{runtime_version}}",
     "measurement": "application.httprequests__one_minute_error_percentage_rate",
     "query": "SELECT  \"value\" FROM \"application.httprequests__percentage_error_requests\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Instance Count ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(application_health_score{env=\"$environment\",app=\"$application\"}) by (container))",
     "legendFormat": "{{app_version}}",
     "measurement": "application.httprequests__one_minute_error_percentage_rate",
     "query": "SELECT  \"value\" FROM \"application.httprequests__percentage_error_requests\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$col",
     "expr": "sum(rate(application_httprequests_transactions_count{env=\"$environment\",app=\"$application\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "1 min rate",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15 min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "expr": "sum(rate(application_httprequests_transactions_count{env=\"$environment\",app=\"$application\",container=~\"$container\"}[5m]))",
     "legendFormat": "5 min rate"
    },
    {
     "expr": "sum(rate(application_httprequests_transactions_count{env=\"$environment\",app=\"$application\",container=~\"$container\"}[15m]))",
     "legendFormat": "15 min rate"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$col",
     "expr": "sum(application_httprequests_transactions{env=\"$environment\",app=\"$application\",container=~\"$container\",quantile=\"0.75\"})",
     "legendFormat": "75th Percentile",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th Percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p98" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "98th Percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "99th Percentile" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "expr": "sum(application_httprequests_transactions{env=\"$environment\",app=\"$application\",container=~\"$container\",quantile=\"0.95\"})",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "sum(application_httprequests_transactions{env=\"$environment\",app=\"$application\",container=~\"$container\",quantile=\"0.99\"})",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Error Rate % per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (route) (application_httprequests_one_minute_error_percentage_rate_per_endpoint{env=\"$environment\",app=\"$application\",container=~\"$container\"} != 0)",
     "legendFormat": "{{container}} {{route}}",
     "measurement": "application.httprequests__one_minute_error_percentage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors by status code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_http_status_code",
     "expr": "sum by (http_status_code) (increase(application_httprequests_error_rate_per_endpoint_and_status_code_total{env=\"$environment\",app=\"$application\",container=~\"$container\"}[$__range]) != 0)",
     "groupBy": [
      { "params": [ "http_status_code" ], "type": "tag" }
     ],
     "legendFormat": "{{http_status_code}}",
     "measurement": "application.httprequests__errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate per sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$col",
     "expr": "sum(rate(application_httprequests_error_rate_total{env=\"$environment\",app=\"$application\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "1min rate",
     "measurement": "application.httprequests__error_rate",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    },
    {
     "expr": "sum(rate(application_httprequests_error_rate_total{env=\"$environment\",app=\"$application\",container=~\"$container\"}[5m]))",
     "legendFormat": "5min rate"
    },
    {
     "expr": "sum(rate(application_httprequests_error_rate_total{env=\"$environment\",app=\"$application\",container=~\"$container\"}[15m]))",
     "legendFormat": "15min rate"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response Time / Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "sum by (route) (application_httprequests_transactions_per_endpoint{env=\"$environment\",app=\"$application\",container=~\"$container\",quantile=\"0.95\"} != 0)",
     "legendFormat": "{{route}}",
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th Percentile" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput / Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "sum by (route) (rate(application_httprequests_transactions_per_endpoint_count{env=\"$environment\",app=\"$application\",container=~\"$container\"}[5m]) != 0)",
     "legendFormat": "{{route}}",
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput / Endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "sum by (route) (rate(application_httprequests_transactions_per_endpoint_count{env=\"$environment\",app=\"$application\",container=~\"$container\"}[$__interval]) != 0)",
     "legendFormat": "{{route}}",
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Request Percentage / Endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "avg by (route) (application_httprequests_one_minute_error_percentage_rate_per_endpoint{env=\"$environment\",app=\"$application\",container=~\"$container\"} != 0)",
     "legendFormat": "{{route}}",
     "measurement": "application.httprequests__one_minute_error_percentage_rate_per_endpoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Times / Endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "sum by (route) (application_httprequests_transactions_per_endpoint{env=\"$environment\",app=\"$application\",container=~\"$container\",quantile=\"0.95\"} != 0)",
     "legendFormat": "{{route}}",
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "PUT & POST Request Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Post Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col",
     "expr": "avg(application_httprequests_post_size{env=\"$environment\",app=\"$application\",container=~\"$container\",quantile=\"0.75\"}) by (quantile)",
     "legendFormat": "75th Percentile",
     "measurement": "application.httprequests__post_size",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p98" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "98th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "99th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "median" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    },
    {
     "expr": "avg(application_httprequests_post_size{env=\"$environment\",app=\"$application\",container=~\"$container\",quantile=\"0.95\"}) by (quantile)",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "avg(application_httprequests_post_size{env=\"$environment\",app=\"$application\",container=~\"$container\",quantile=\"0.99\"}) by (quantile)",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Put Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "expr": "avg(application_httprequests_put_size{env=\"$environment\",app=\"$application\",container=~\"$container\",quantile=\"0.75\"}) by (quantile)",
     "legendFormat": "75th Percentile",
     "measurement": "application.httprequests__put_size",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p98" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "98th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "99th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "median" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    },
    {
     "expr": "avg(application_httprequests_put_size{env=\"$environment\",app=\"$application\",container=~\"$container\",quantile=\"0.95\"}) by (quantile)",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "avg(application_httprequests_put_size{env=\"$environment\",app=\"$application\",container=~\"$container\",quantile=\"0.99\"}) by (quantile)",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Health Checks",
   "type": "table",
   "description": "For more information about how to add health checks please refer to the links below:\n* https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks \n* https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_health_check_name",
     "expr": "avg(application_health_results {env=\"$environment\", app=\"$application\", container=~\"$container\"}) by (health_check_name)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "health_check_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{health_check_name}}",
     "measurement": "application.health__results",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  { "title": "DotNet Runtime Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Number of open handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_open_handles{env=\"$environment\",app=\"$application\",container=~\"$container\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_num_threads {env=\"$environment\",app=\"$application\",container=~\"$container\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dotnet_cpu_percentage {env=\"$environment\",app=\"$application\",container=~\"$container\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Process working set (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "dotnet_working_set_bytes{env=\"$environment\",app=\"$application\",container=~\"$container\"} /1024/1024",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Private memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "dotnet_private_memory_bytes {env=\"$environment\",app=\"$application\",container=~\"$container\"} /1024/1024",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Virtual memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "dotnet_virtual_memory_bytes {env=\"$environment\",app=\"$application\",container=~\"$container\"} /1024/1024",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}